#!/usr/bin/env python
from devices import get_devices

if __name__ == "__main__":
    devices = get_devices()
    for name, handlers in devices.items():
        print("{}: {}".format(name, handlers))
